name: macos intel build
on:
  - push
jobs:
  bunddle_app:
    runs-on: macos-15-intel
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Setup Dependency
        run: |
          python -m pip install -r requirements-qqdebreath.txt
      - name: build app
        run: |
          python3 -m PyInstaller --noconfirm --clean QQDeBreathTool.spec
      - name: prepare dmg
        run: |
          mkdir dmg_structure
          mv dist/QQDeBreathTool.app ./dmg_structure
          TARGET_PATH="/Applications"
          ALIAS_DIR="dmg_structure"
          ALIAS_NAME="Applications"
          osascript -e 'tell application "Finder" to make new alias file at desktop to POSIX file "/Applications" with properties { name: "Applications" }'
          mv ~/Desktop/Applications ./dmg_structure
          hdiutil create -volname "QQDeBreathTools_MacOS_intel" -srcfolder dmg_structure -ov -format UDZO QQDeBreathTools_MacOS_intel.dmg
      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: QQDeBreathTools_MacOS_intel.dmg
